apiVersion: v1
kind: Pod
metadata:
  name: dummy-app
  labels:
    app: dummy-app
    app.kubernetes.io/name: dummy-app
spec:
  containers:
    - name: dummy-app
      image: fajarhide/demo-dt:v2
      ports:
        - name: dummy-app
          containerPort: 8000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-distributed-tracing
spec:
  selector:
    app.kubernetes.io/name: dummy-app
  ports:
  - name: http
    protocol: TCP
    port: 8000